#БДшка
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: tourguide_db
    restart: always
    environment:
      POSTGRES_USER: tacohed
      POSTGRES_PASSWORD: tacohed
      POSTGRES_DB: tourguide
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tacohed -d tourguide"]
      interval: 5s
      timeout: 5s
      retries: 5

#Бэк
  backend:
    build: .  
    container_name: tourguide_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HF_HOME=/app/hf_cache #чтобы модель здесь хранил
      - DATABASE_URL=postgresql+asyncpg://tacohed:tacohed@db:5432/tourguide
    # для теста
    volumes:
      - ./:/app  
      - hf_cache:/app/hf_cache #а на самом деле в докере
      - /app/.venv
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 

  #Фронт
  frontend:
    build:
      context: ./frontend      
      target: build-stage      # чтобы брать Node.js, а не Nginx  
    container_name: tourguide_frontend
    restart: always
    ports:
      # - "80:80" 
      - "5173:5173"   # поменял пока порт на vite для теста и чтобы винда не душила сообщениями на 80 порту
    depends_on:
      - backend
      # для теста
    volumes:
      - ./frontend:/app           
      - /app/node_modules         
    command: npm run dev -- --host 
    environment:
      - CHOKIDAR_USEPOLLING=true  # чтобы винда видела изменения файлов

  #Админка БД
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: tourguide_pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: admin@admin.com
#       PGADMIN_DEFAULT_PASSWORD: admin
#     ports:
#       - "5050:80"
#     restart: always

volumes:
  postgres_data:
  hf_cache: #сохранение модели в докере(-v не юзать)